version: '3'
name: kafka
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-network
  broker1:
    container_name: broker1
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Essa variável é utilizada para especificar os endereços (hostnames e portas)
      # aos quais os clientes Kafka (produtores e consumidores) devem se conectar,
      # para que acessem o broker Kafka.
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:9092
    networks:
      - kafka-network
    depends_on:
      - zookeeper
networks:
  kafka-network:
    driver: bridge
    name: kafka-network
